### ISSUE TITLE
Option to keep list characters

### ISSUE THREAD

**Issue by samuelmeuli** [wooorm/strip-markdown#15]
### Subject of the feature

Option to keep list characters

### Problem

I'm using this module for a feature for exporting Markdown to TXT. Unfortunately, after processing the MD with this plugin, lists are no longer recognizable as such because the list characters (e.g. `- `) are removed.

### Expected behaviour

I understand that removing this information is what the plugin is supposed to do. For my use case, however, it would be nice to have an option to keep these list characters in the output.

I completely understand if this is not something you'd like to integrate or if you'd rather not provide options for the plugin. If so, feel free to close this issue :)

**Comment by wooorm** [comment]
Hi Samuel!

I was going to write kinda what you mentioned in the expected behaviour section 😉

*Why* do you want to remove markdown formatting but keep some of it? Why not keep it all?

**Comment by samuelmeuli** [comment]
One could argue that list characters aren't just formatting but describe the structure of the text. A text with and without lists reads very differently IMO.

**Comment by wooorm** [comment]
That’s true!

For a while I used to markup lists like so:

```
Get things from the grocery store:

- milk;
- eggs;
- whiskey.
```

To match a prose version of that list: `Get things from the grocery store: milk; eggs; whiskey.`

---

Could you expand on what you‘re trying to do? Why are you removing syntax?

**Comment by samuelmeuli** [comment]
I have written a [diary app](https://github.com/samuelmeuli/mini-diary) which stores entries in Markdown and allows you to export in various formats, including to TXT files. For that text export, I would like to remove all formatting, but keep the lists.

**Comment by wooorm** [comment]
Cool project!

Is it really needed to strip markdown syntax? Isn‘t \*important\* seen as that by people even in text? And sometimes it works, like Slack or WhatsApp and the like...

**Comment by samuelmeuli** [comment]
Thanks, @wooorm!

I generally agree with you. The plain-text export is handled as described by other journal apps (Day One, jrnl) tough, which is why I implemented it that way. I had removed the feature at some point, only offering exporting to Markdown, and got requests to add the feature back.

I totally see your point and understand if you'd rather not have that option in this plugin, and I wouldn't mind continuing to use a fork of it :)

**Comment by wooorm** [comment]
Interesting.
Would it end at lists, or are there other things you’d like to keep (or change) for plaintext?
For example: uppercase headings? Keep thematic breaks?

**Comment by samuelmeuli** [comment]
Just lists. The only Markdown features I've enabled in the editor are bold, italics and lists, and I'm not planning to add any others.

**Comment by wooorm** [comment]
Right!

What do you think of a `keep` option?

```js
remark()
  .use(strip, {keep: ['list', 'listItem']})
  .process('Some *emphasis*, **importance**, and `code`.', function(err, file) {
```

**Comment by samuelmeuli** [comment]
I like it 👌 I can work on a PR for this if you'd like.

**Comment by wooorm** [comment]
A PR would be welcome! I’m thinking the direction to go would be to move everything into the `strip` function:

https://github.com/remarkjs/strip-markdown/blob/f92f73b1a38d6a05015cf2d4c5888c282bd38e56/index.js#L5-L7

Like so:

```js
 function strip(options) { 
   var keep = (options || {}).keep || []

   return one 

   ...
 } 
```

And then only adding keys to `map` if they‘re not in `keep`.

**Comment by kratam** [comment]
> Interesting. Would it end at lists, or are there other things you’d like to keep (or change) for plaintext? For example: uppercase headings? Keep thematic breaks?

I know this is an old issue, but in my use case, I'd like to extract urls from links. Let's say I have a MD like this:
`more information [here](https://foo.bar)`
When I convert this to plaintext (so it can be sent over plaintext platforms), the url can't be seen.

**Comment by wooorm** [comment]
- this issue has a linked pr that was merged and is released, does that not solve what you want?
- `so it can be sent over plaintext platforms` — markdown can also be sent, I’m not sure I get your use case?

**Comment by kratam** [comment]
Use case: I have markdown message templates that can be sent to customers. Some customers receive the messages via email or see them in a browser while others receive via SMS (text).

Some templates contain parts like this: `here is an [important link](https://foo.bar).`.

For HTML enabled channels (e.g. email or browser) I convert the markdown to HTML via rehype. They receive the above example like this:

> here is an [important link](https://foo.bar).

But if I convert the markdown to plain text to be sent as an SMS, they receive it like this:

> here is an important link.

Obviously, I'd like to show the message like this (because the href is not just formatting which can be stripped, it's essential part of the message):

> here is an important link (https://foo.bar).

**Comment by wooorm** [comment]
Thanks, I understand the use case. It’s a bit different from what this issue is discussing (lists) and what its solution does (allowing certain nodes), because you want to change the tree.
You can do so, by creating your own plugin that handles links the way you want — perhaps you can also write a PR to include such functionality here.
