### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by samuelmeuli** [wooorm/strip-markdown#16]
First of all, thanks a lot for the work on Remark!

I've seen that Remark now has TypeScript definitions included since the latest release. It would be great if they could also be added to this plugin :)

**Comment by wooorm** [comment]
Thanks Samuel, appreciated!

TS is being added to the unified collective. That’s 250 repos, so it takes some time.

There are a couple of people working on this, @ChristianMurphy and @Rokt33r, but we’d appreciate contributors too. If you have the time, a PR would be welcome.

I’m going to close this as people are working on it, but 250 open issues doesn’t make a lot of sense to me!

**Comment by samuelmeuli** [comment]
I totally understand – I can have a look at it. Do you guys have a reference repo for setup/configuration?

**Comment by ChristianMurphy** [comment]
@samuelmeuli take a look at https://github.com/remarkjs/remark-lint/pull/215
