### ISSUE TITLE
Fix exception for parents without children

### ISSUE THREAD

**Issue by stefanprobst** [wooorm/strip-markdown#18]
### Subject of the issue

When `strip-markdown` encounters a `link` node without children, it [throws](https://github.com/remarkjs/strip-markdown/blob/4afb37d8e1d431de4814e4a16f0869a7a2c266c2/index.js#L63) `Cannot use 'in' operator to search for 'length' in undefined`. This is because `mapFiltered.link` expects `node.children`.

### Your environment

*   **OS**: Linux
*   **Packages**: `strip-markdown@3.1.0`, `unified@8.3.2`
*   **Env**: Node 10.16.3

### Steps to reproduce
```js
const unified = require('unified')
const strip = require('strip-markdown')

const ast = {
  type: 'root',
  children: [
    {
      type: 'link',
      url: '#hash-link',
      title: null,
      data: {
        hProperties: {
          'aria-label': 'some info',
          class: 'anchor'
        },
        hChildren: [
          {
            type: 'raw',
            value: '<svg></svg>'
          }
        ]
      }
    }
  ]
}

unified()
  .use(strip)
  .runSync(ast)
```

### Expected behaviour
Don't crash

### Actual behaviour
Crash

**Comment by wooorm** [comment]
Hi Stefan, I removed the exception, but you’ll probably run into this with other projects because your syntax tree is invalid. You’re better off fixing that. [Links are required to have children](https://github.com/syntax-tree/mdast#link).

**Comment by stefanprobst** [comment]
hi titus, thanks for your quick response! the ast was something i got out of gatsby's remark transformer, so i'll have a look what goes wrong there. thanks again
