### ISSUE TITLE
Add typescript types

### ISSUE THREAD

**Issue by roshcagra** [wooorm/strip-markdown#20]
### Subject of the feature

Typescript support

### Problem

No typing support for this module :(

**Comment by ChristianMurphy** [comment]
@roshcagra pull requests are welcome!
You can find some examples of other typings to base these typings off of:
https://github.com/remarkjs/remark-breaks/pull/1
https://github.com/remarkjs/remark-frontmatter/pull/12
https://github.com/remarkjs/remark-rehype/pull/13
https://github.com/remarkjs/remark-html/pull/32
