### ISSUE TITLE
Does not seem to remove tables

### ISSUE THREAD

**Issue by donorman** [wooorm/strip-markdown#22]
```
var remark = require('remark')
var strip = require('strip-markdown')

remark()
  .use(strip)
  .process('|a|s||-|-||a|a|', function(err, file) {
    if (err) throw err
    console.log(String(file))
  })
```

**Comment by ChristianMurphy** [comment]
Please fill out the issue template when opening issues.
And also note that, when using GitHub flavored markdown features, like tables, `remark-gfm` is needed.
https://codesandbox.io/s/strip-markdown-tables-6z1oe

**Comment by donorman** [comment]
Thanks a lot! Got it working using remark-gfm. Sorry about the template. Good work, keep it up, really appreciate it!
