### ISSUE TITLE
Add remark as peer dependency

### ISSUE THREAD

**Issue by micalevisk** [wooorm/strip-markdown#24]
> This is not exactly a feature btw

Hey! Since this lib is a plugin to another one (`remark`) it would be nice to put `remark` as a [peer dependecy](https://nodejs.org/es/blog/npm/peer-dependencies/#the-solution-peer-dependencies) thus users will be aware of which version of `remark` is supported ^^

basically `npm install --save-peer remark@^13.0.0`

**Comment by wooorm** [comment]
Hi there!

Weird as it may sound, this plugin does not need `remark` as a peer dependency. There are several ways of using it without that package.
Over the years, we (at least I) also had some bad experiences with them (such as https://github.com/remarkjs/remark/issues/35, https://github.com/syntax-tree/unist-util-is/issues/14#issuecomment-581351139, and more).

So thanks for the suggestion but I don’t think it makes sense for us!
