### ISSUE TITLE
Backslash prepended to the input `[`

### ISSUE THREAD

**Issue by srmagura** [wooorm/strip-markdown#28]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark@14.0.2, strip-markdown@5.0.0

### Steps to reproduce

1. Go to the playground: http://remarkjs.github.io/strip-markdown/
2. Enter `[`

### Expected behavior

The output is `[`.

### Actual behavior

The output is `\[`.

I am not sure if this is intentional escaping or a bug.

I have a string of Markdown, and I want to convert it to plain text. With the current behavior, I will end up displaying backslashes that were not in the original text.

### Runtime

Node v16

### Package manager

yarn 2

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by ChristianMurphy** [comment]
The escaping is intentional.
Some more context on a recent question asking the same thing: https://github.com/orgs/syntax-tree/discussions/87

Repeating some of that here:

> Taking a step back, `remark` is an AST ecosystem.
> Meaning it will preserve the structure/presentation of the content, but will not retain the exact characters.
> You can read more about this is some previous discussions on AST vs CST.
https://github.com/remarkjs/remark/search?q=cst&type=issues and https://github.com/orgs/remarkjs/discussions?discussions_q=cst
>
> In this case the escaped output is fine, it doesn't matter if it is escaped, the final presentation will be the same.

Adding on some additional context, if you are looking for full plain text rather than stripped down markdown text.
Consider using https://github.com/syntax-tree/mdast-util-to-string rather than `remark-stringify` to generate plain text rather than markdown text.

**Comment by srmagura** [comment]
Thanks @ChristianMurphy! `mdast-util-to-string` is doing exactly what I needed:

```ts
const tree = fromMarkdown(markdown);
return toString(tree);
```

**Comment by ninja7dev** [comment]
> Thanks @ChristianMurphy! `mdast-util-to-string` is doing exactly what I needed:
> 
> ```ts
> const tree = fromMarkdown(markdown);
> return toString(tree);
> ```

unfortunately that solution doesn't preserve new lines, as I would need.

**Comment by remcohaszing** [comment]
Just like escape characters, newlines single don’t have meaning in markdown. Although it’s not recommended, you can give them meaning using [`mdast-util-newline-to-break`](https://github.com/syntax-tree/mdast-util-newline-to-break).
