### ISSUE TITLE
Keep existing new lines when thematic breaks are removed

### ISSUE THREAD

**Issue by chmanie** [wooorm/strip-markdown#29]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently, when headings are removed, the text is just concatenated.
Edit: Sorry, this might actually be a bug. It only happens if there are `thematicBreak`s and they are being removed (default).

Example:
```
# Foo

## Bar

---

## Testing
```

becomes

`FooBarTesting`

### Solution

I'm not sure exactly, I will investigate.

### Alternatives

**Comment by wooorm** [comment]
I don‘t think this project does that. Feel free to report back if that’s the case!

**Comment by chmanie** [comment]
Here's a stackblitz pad that reproduces that behavior: https://stackblitz.com/edit/node-1tyzwy?file=index.js

**Comment by wooorm** [comment]
Released in https://github.com/remarkjs/strip-markdown/releases/tag/5.0.1!

**Comment by chmanie** [comment]
Oh wow, thank you so much!
