### ISSUE TITLE
* is converted to \* when trying to strip markdown?

### ISSUE THREAD

**Issue by AnderssonPeter** [wooorm/strip-markdown#32]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark: 15.0.1, strip-markdown: 6.0.0

### Steps to reproduce

Run the following code `remark().use(strip).processSync("Testing*").toString().trimEnd()`
I'm using Node 20 and npm 10.2.4 and the code was run in Chrome 123.0.6312.107

### Expected behavior

the result should be `Testing*`

### Actual behavior

The result is `Testing\*`

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
yep, search through closed issues — this package still generates markdown, so that `*` is escaped. That may or may not be what you want

**Comment by AnderssonPeter** [comment]
@wooorm i check the issues, but only read the titles, and none of them seemed like the same issue, but i guess i was wrong..
Are there any other things i need to look out for when using the output or is it just that * is escaped?

**Comment by wooorm** [comment]
See https://github.com/remarkjs/strip-markdown/issues/28 for example.

Yes, every punctuation character that seems to do something in markdown is escaped to prevent it from doing something.

**Comment by AnderssonPeter** [comment]
Thanks for the response.

**Comment by ninja7dev** [comment]
Could we please make an option to disable the char escaping if needed?
I'm trying to extract the text from a markdown chunk and getting "`H\&M`" instead of "`H&M`". What can i do?

**Comment by ChristianMurphy** [comment]
@ninja7dev please stop adding comments everywhere remotely related to your question.
Open **one** new discussion, articulate your use case, so the community can offer suggestions.
