### ISSUE TITLE
option to disable escaping

### ISSUE THREAD

**Issue by ninja7dev** [wooorm/strip-markdown#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'm trying to extract the text from a markdown chunk and getting "`H\&M`" instead of "`H&M`".
The actual code:
```
import { remark } from 'remark';
import strip from 'strip-markdown';

const content = remark()
  .use(strip)
  .processSync('**H&M**');
console.log(String(content));
```

### Solution

Could we please make an option to disable the char escaping, for those who need it?
I saw some older issues/discussions created around this repo but couldn't find a working solution.

### Alternatives

-

**Comment by wooorm** [comment]
Why do you want what you want?

Indeed, this plugin still generates markdown. That is intended. It removes the working things, so headings turn into paragraph.

Some humans want what you want. Some users want what is happening right now.

It’s not possible to do what you want here. This is not the place that deals with escapes.

**Comment by ninja7dev** [comment]
> Why do you want what you want?

I need to display to the users a plain-text representation from the markdown. Hence, it should be user-friendly, easy to read, the text from headings and paragraphs should have their own rows etc.

> Some humans want what you want. Some users want what is happening right now.

I understand and agree. In fact this is exactly why I was asking for a configurable option, so the default behavior doesn't need to be changed. I went through the older discussions that were related to escaping.

> It’s not possible to do what you want here. This is not the place that deals with escapes.

Okay. Could you please point me to the right direction, how could i achieve what i need, using remark and maybe some of the related plugins?
I find it a bit hard to believe that this isn't doable this with such variety of tools.

**Comment by wooorm** [comment]
> I find it a bit hard to believe that this isn't doable this with such variety of tools.

It’s vague what “this” is. You call it “plain-text representation”. HTML is a standard. Markdown mostly standards but also at least reference implementations and agreements. Plain-text is not a standard.

For me to answer you thoroughly, we’d need to cover all possible markdown input cases. Talk about what output you want for each possibility. Then we can make that. Now I don’t know what “representation” you have in your head.

> I need to display to the users a plain-text representation from the markdown.

As you say “display”, why not get HTML out:

```js
import { unified } from "unified";
import remarkParse from "remark-parse";
import stripMarkdown from "strip-markdown";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";

const file = unified()
  .use(remarkParse)
  .use(stripMarkdown)
  .use(remarkRehype)
  .use(rehypeStringify)
  .processSync("**H&M**");

console.log(String(file));
```

```html
<p>H&#x26;M</p>
```

**Comment by ninja7dev** [comment]
Let me try to clarify: what i mean by plain-text representation / version is, actually, only the text with no markup (be that markdown or HTML).
Examples:
markdown heading -> normal text
bold text -> normal text
italic text -> normal text
blockquote -> normal text
paragraph -> normal text
image -> removed 
link -> normal text 

However, as i mentioned in a previous message, a block part like the heading should be on its own row, not mixing up with the next paragraph, for example.

**Comment by wooorm** [comment]
Well, that’s all a bit short, but I think that matches the HTML example I have, as it gives you HTML that you can display to users, those `<p>`s are the paragraphs you talk about.

**Comment by remcohaszing** [comment]
@ninja7dev It looks like you’re not trying to produce markdown, so you don’t need to handle escaping. I think you’re looking for something like this:

```js
import {fromMarkdown} from 'mdast-util-from-markdown'
import {toString} from 'mdast-util-to-string'

const ast = fromMarkdown('**H&M**')
const content = toString(ast)
```

**Comment by ninja7dev** [comment]
> Well, that’s all a bit short, but I think that matches the HTML example I have, as it gives you HTML that you can display to users, those `<p>`s are the paragraphs you talk about.

It seems like this still returns markup (HTML).
I was looking to obtain, as i wrote in my previous message,  _only the text with no markup (be that markdown or HTML)._ (i meant only the text with neither markdown, nor HTML, nor any other type of markup.



> @ninja7dev It looks like you’re not trying to produce markdown, so you don’t need to handle escaping. I think you’re looking for something like this:
> 
> ```js
> import {fromMarkdown} from 'mdast-util-from-markdown'
> import {toString} from 'mdast-util-to-string'
> 
> const ast = fromMarkdown('**H&M**')
> const content = toString(ast)
> ```

Thank you, but I've had previously tried this solution. It results in inlining headings, paragraphs, lists into a big paragraph of text.
It's not preserving the text from the block type parts on their own rows.

**Comment by remcohaszing** [comment]
> Thank you, but I've had previously tried this solution. It results in inlining headings, paragraphs, lists into a big paragraph of text. It's not preserving the text from the block type parts on their own rows.

So I understand it’s close to what you want? It’s just not exactly what you want. [`mdast-util-to-string`](https://github.com/syntax-tree/mdast-util-to-string/blob/main/lib/index.js) is not very complex. You can create your own implementation and use that as a base.

**Comment by wooorm** [comment]
Closing as this issue seems not actionable after discussing it for a while.
