### ISSUE TITLE
Strikethrough not handled properly

### ISSUE THREAD

**Issue by MichalPaszowski** [wooorm/strip-markdown#34]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"strip-markdown": "^6.0.0", "remark": "^14.0.3",

### Steps to reproduce

Parsing
`~~test~~`
results in:
`\~~test~~`

### Expected behavior

Parsing
`~~test~~`
should result in:
`test`

### Actual behavior

Parsing
`~~test~~`
results in:
`\~~test~~`

### Affected runtime and version

chrome 129.0.6668.90

**Comment by wooorm** [comment]
Strikethrough is not a markdown (commonmark) feature, so it is not available by default. You are looking for `remark-gfm`, as it is a GFM feature
